### ISSUE TITLE
 Error trying to create key and CipherData, by hexadecimal method

### ISSUE THREAD

**Issue by gmarcinari** [superk589/RijndaelSwift#4]
Hi, the error is in the hexadecimal method on these lines

` let key = "Tr!issT@anNer4".hexadecimal()!`
`let cipherData = arrayCode[1].hexadecimal()!`

NSLog(arrayCode[1]) = "IDjDQ4E6c7b2oO7LyojQ2g=="

_Fatal error: Unexpectedly found nil while unwrapping an Optional value_

```
internal func codeDecrypt(code: String) -> String{
        let arrayCode : [String] = code.components(separatedBy: "ambiente=")
        
        let str = String(describing: "T!risT4Ner@".cString(using: String.Encoding.utf8))
        
        //i tried this too -  let key = "T!risT4Ner@".hexadecimal()! - same error
        let key = str.hexadecimal()!
        let iv = "7898523212584568".hexadecimal()!
        let r = Rijndael(key: key, mode: .cbc)!
        
        let cipherData = arrayCode[1].hexadecimal()!
        let plainData = r.decrypt(data: cipherData, blockSize: 32, iv: iv)
        
        return plainData!.hexadecimal()
    }
```

how should I proceed ?

Thanks

**Comment by superk589** [comment]
IDjDQ4E6c7b2oO7LyojQ2g== 
This is like a base64 encoded string, not a hex string, try the code below:
```
let cipherData = Data(base64Encoded: "IDjDQ4E6c7b2oO7LyojQ2g==")
```

**Comment by gmarcinari** [comment]
Thanks for the quick response, I made some changes, the previous error no longer exists. The result of the decryption is different than expected.

  ```
 internal func codeDecrypt(code: String) -> String{
        let base64Code : [String] = code.components(separatedBy: "ambiente=")

        let keyStr = "Gpss!st3m@ssssss".utf8
        let ivStr = "7898523212584568".utf8

        let key =  Data(keyStr)
        let iv = Data(ivStr)

        NSLog(base64Code[1]) // "mdRpAc15dO5DrXc+Ad5oqg=="
        
        let cipherData = Data(base64Encoded: base64Code[1])!
        
        let r = Rijndael(key: key, mode: .cbc)!
        
        let plainData = r.decrypt(data: cipherData, blockSize: 16, iv: iv)
        
        return String(decoding: plainData!.split(separator: 0)[0], as: UTF8.self)
        
    }
```

_result "\apK\u{ef}8\u{ef}\u{12}=\u{ef}\u{ef}\u{ef}!R\u{ef}uc"_


I am encrypting with the same password key in server side.
On the server side I am encrypting a simple string like "356" using the following code in C#:

//Create Crypto
`var criptografia = new Crypto(password);`

//Constructor Crypto
```
public Crypto(string password)
        {
            //Encode digest
            var md5 = new MD5CryptoServiceProvider();
            _password = md5.ComputeHash(Encoding.ASCII.GetBytes(password));

            //Initialize objects
            _cipher = new RijndaelManaged();
            decryptor = cipher.CreateDecryptor(_password, IV);
            encryptor = cipher.CreateEncryptor(_password, IV);

        }
```
//encryption call
`criptografia.Encrypt("356")`


```
 public string Encrypt(string text)
{
     var buffer = Encoding.ASCII.GetBytes(text)
     return Convert.ToBase64String(Encryptor.TransformFinalBlock(buffer, 0, buffer.Length));
}
```

In the android application I am using the RijndaelCrypt library to decrypt, and I succeeded.

Am I doing something wrong?

**Comment by gmarcinari** [comment]
I realized something was missing that was the conversion of my password to MD5, but the result is still not as expected


```
 internal func codeDecrypt(code: String) -> String{
        let base64Code : [String] = code.components(separatedBy: "ambiente=")

        let key = MD5("Gpss!st3m@s")
        let iv = Data("7898523212584568".utf8)
        
        let cipherData = Data(base64Encoded: base64Code[1])!
        
        let r = Rijndael(key: Data(key.utf8), mode: .cbc)!
        
        let plainData = r.decrypt(data: cipherData, blockSize: 16, iv: iv)
        
        return String(decoding: plainData!.split(separator: 0)[0], as: UTF8.self)
        
    }
```

returns String	"C\u{ef}\u{ef}Cߍ\u{ef}Ȃk\u{ef}\u{11}\u{ef}\u{ef}\u{ef}Y"

**Comment by superk589** [comment]
`
        return String(decoding: plainData!.split(separator: 0)[0], as: UTF8.self)
`

try to replace it to 
`
        return String(plainData!.split(separator: 0)[0], encoding: .utf8)
`

**Comment by superk589** [comment]
Besides, if you use block size of 128 bit, you can also try some standard AES libraries. This library is created specially for the uncommon use of 256 block size Rijndael Algorithm.

**Comment by superk589** [comment]
I’m closing this issue because it has been inactive for a few months.
Please reopen if you still encounter any issue related to this one.
Thank you!
